### ISSUE TITLE
Can't integrate with Peario.

### ISSUE THREAD

**Issue by Castrum95** [TheBeastLT/stremio-kitsu-anime#19]
Hi. I don't know if it's an issue since it's compatibility between addons.

I think the problem here is the method of cataloging, Peario only has options for movies and series, since Kitsu it's centralized under the "anime" tag, the series and movies doesn't show up.
I respect the decision of mantaining them under the anime section as it keeps the media all together, but sometimes it's a mess to search some seasons between all other mixed up with the films, and having them organised in the search bar separated over series and films would be great. In the other hand there would be some anime showing up over the discover menu, but you could just keep scrolling if you are not interested on anime, just like in netflix.

Also, I've some suggestions for adding some torrent repositories with spanish sub since there is no much content in the platform and I don't know where should I aks for this, would it be possible? I can also help with that.

**Comment by TheBeastLT** [comment]
This is not an issue with this addon. Please contact peario dev for this.
Regarding catalogs, it will stay under anime type, as more people prefer for it to be distinct.
