### ISSUE TITLE
kitsu-anime-list : Descending Sort

### ISSUE THREAD

**Issue by heavy-baby** [TheBeastLT/stremio-kitsu-anime#2]
'Kitsu' catalog always shows old series at first.
Please consider latest anime series at the top.

```
const sortValue = {
	'kitsu-anime-list': 'createdAt', **<== THIS POINT**
	'kitsu-anime-rating': '-average_rating',
	'kitsu-anime-popular': '-user_count'
};

```

**Comment by TheBeastLT** [comment]
That's expected, as it's the main list it's sorted by entry's creation date. You can use  trending catalog to see newer animes.
