### ISSUE TITLE
Calendar and notifications not showing any data

### ISSUE THREAD

**Issue by lsop0** [TheBeastLT/stremio-kitsu-anime#22]
When adding a series to the library you don't get notifications nor they appear in the calendar even that the release date for the chapters is there.

Jujutsu Kaisen in the page from Cinemata, notice the button to set notifications over the selection of the season
![image](https://github.com/TheBeastLT/stremio-kitsu-anime/assets/80780570/87a7f292-d446-45df-8be0-a8cf025562ba)

Jujutsu Kaisen Season 2 in theKitsu addon
![image](https://github.com/TheBeastLT/stremio-kitsu-anime/assets/80780570/45972e9f-a502-4bb1-bc4d-88195be079e5)

**Comment by TheBeastLT** [comment]
This functionality is only supported for official cinemeta addon. Community addons cannot appear there atm.
